#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: gateway-impersonate
#rules:
#- apiGroups:
#  - ""
#  resourceNames:
#  - gateway-connect-agent@anthos-bare-metal-lab-1.iam.gserviceaccount.com
#  resources:
#  - users
#  verbs:
#  - impersonate
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: gateway-impersonate
#roleRef:
#  kind: ClusterRole
#  name: gateway-impersonate
#  apiGroup: rbac.authorization.k8s.io
#subjects:
#- kind: ServiceAccount
#  name: connect-agent-sa
#  namespace: gke-connect
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: gateway-cluster-admin-abm-lab-1
#subjects:
#- kind: User
#  name: gateway-connect-agent@anthos-bare-metal-lab-1.iam.gserviceaccount.com
#roleRef:
#  kind: ClusterRole
#  name: cluster-admin
#  apiGroup: rbac.authorization.k8s.io
#
